Repository libp2p/specs, pull requests merged in 2019-06, with the labels that each got.

#171 libp2p specs framework: document header format
  00-framework-02-document-header.md
Labels: maturity:working draft

#106 SECIO spec
  secio/README.md
Labels: in progress, maturity:recommendation

#100 docs: add peer id spec
  README.md
  peer-ids/peer-ids.md
Labels: in progress
